# Generated by Django 4.2.1 on 2023-07-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customerreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerReviews',
            new_name='CustomerReview',
        ),
    ]
