# Generated by Django 4.2.1 on 2023-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_customerreviews_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorder',
            name='channel',
            field=models.CharField(choices=[('WB', 'Website'), ('IN', 'Instagram'), ('FB', 'Facebook'), ('TK', 'Tiktok')], default=('WB', 'Website'), max_length=255),
        ),
        migrations.AlterField(
            model_name='confirmedorder',
            name='status',
            field=models.CharField(choices=[('OC', 'Order Confirmed'), ('SC', 'Shipped to Courier'), ('RC', 'Received by Customer')], default=('OC', 'Order Confirmed'), max_length=255),
        ),
    ]
