# Generated by Django 4.2.1 on 2023-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_confirmedorder_channel_alter_confirmedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='channel',
            field=models.CharField(choices=[('WB', 'Website'), ('IN', 'Instagram'), ('FB', 'Facebook'), ('TK', 'Tiktok')], default=('WB', 'Website'), max_length=255, null=True),
        ),
    ]
