# Generated by Django 4.2.1 on 2023-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_color_productvariant_stock_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='UN', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
