# Generated by Django 4.2.1 on 2023-08-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_code_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
