# Generated by Django 4.2.1 on 2023-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_color_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(default='', upload_to='colors/'),
        ),
    ]
