# Generated by Django 4.2.1 on 2023-08-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.productvariant'),
        ),
    ]
