# Generated by Django 4.2.1 on 2023-08-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
