# Generated by Django 4.2.1 on 2023-08-31 13:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_productimages_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_large',
            field=models.ImageField(blank=True, upload_to=core.models.product_variant_image_directory),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_medium',
            field=models.ImageField(blank=True, upload_to=core.models.product_variant_image_directory),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_original',
            field=models.ImageField(default='', upload_to=core.models.product_variant_image_directory),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_small',
            field=models.ImageField(blank=True, upload_to=core.models.product_variant_image_directory),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to=core.models.product_variant_image_directory),
        ),
    ]
