# Generated by Django 4.2.1 on 2023-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
