# Generated by Django 4.2.1 on 2023-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_shipping_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_days',
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
