# Generated by Django 4.2.1 on 2023-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_product_shipping_days_product_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
