# Generated by Django 4.2.1 on 2023-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_productvariant_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorder',
            name='tracking_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
