# Generated by Django 4.2.1 on 2023-09-02 06:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_confirmedorder_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_xsmall',
            field=models.ImageField(blank=True, upload_to=core.models.product_variant_image_directory),
        ),
        migrations.AlterField(
            model_name='confirmedorder',
            name='tracking_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
