# Generated by Django 4.2.1 on 2023-09-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_confirmedorder_tracking_id'),
        ('core', '0027_productvariant_image_xsmall_and_more'),
    ]

    operations = [
    ]
