# Generated by Django 4.2.1 on 2023-09-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20230902_0644'),
        ('core', '0029_alter_productvariant_old_price_and_more'),
    ]

    operations = [
    ]
