# Generated by Django 4.2.1 on 2023-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_productimage_alt_tag_productvariant_alt_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_tag', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
