# Generated by Django 4.2.1 on 2023-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpolicy',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='shippingpolicy',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingpolicy',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingpolicy',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
