# Generated by Django 4.2.1 on 2023-09-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='description',
        ),
    ]
