# Generated by Django 4.2.1 on 2023-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="alt_tag",
            field=models.CharField(default="", max_length=255),
        ),
    ]
