# Generated by Django 4.2.1 on 2023-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_homepage_alt_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="secondary_banner",
            field=models.ImageField(default="", upload_to="main_page/"),
        ),
    ]
