# Generated by Django 4.2.1 on 2023-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_homepage_secondary_banner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="secondary_banner",
            new_name="secondary_desktop_banner",
        ),
        migrations.AddField(
            model_name="homepage",
            name="secondary_mobile_banner",
            field=models.ImageField(default="", upload_to="main_page/"),
        ),
    ]
