# Generated by Django 4.2.1 on 2023-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(max_length=255)),
                ('image', models.ImageField(upload_to='ig_posts/')),
                ('display', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt_tag', models.CharField(max_length=255)),
            ],
        ),
    ]
