# Generated by Django 4.2.1 on 2023-09-19 12:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='image',
            field=models.ImageField(upload_to=api.models.ig_post_directory),
        ),
    ]
