# Generated by Django 4.2.1 on 2023-09-19 12:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_igpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpost',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=api.models.ig_post_directory),
        ),
    ]
