# Generated by Django 4.2.1 on 2023-09-20 16:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_igpost_thumbnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igpost',
            old_name='image',
            new_name='medium_image',
        ),
        migrations.AddField(
            model_name='igpost',
            name='original_image',
            field=models.ImageField(default='', upload_to=api.models.ig_post_directory),
        ),
    ]
