# Generated by Django 4.2.1 on 2023-09-20 16:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_igpost_medium_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='medium_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=api.models.ig_post_directory),
        ),
    ]
